# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - name: Update PIP
      run: |
        python3 -m pip3 install --upgrade pip3
    - name: Run code
      run: |
        python3 PrincessPaperplane/paperbot.py -test
